config/routes.rb
Rails.application.routes.draw do
	devise_for :users  
  devise_for :admins
  root to: 'posts#index'

  post 'pusher/auth' => 'presence#auth'
  
  resources :posts do
  	resource :maps
  	resources :charges
  	resources :likes
  end

  resources :news

  resources :follows

  resources :orders
  resources :tags

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post

  include PublicActivity::Common
  # tracked

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_create :send_confirmation_email

  def send_confirmation_email
  	OrderMailer.confirmation(self).deliver
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, 
		styles: {thumb: "300x300>"}, 
		storage: :s3,
		s3_credentials: {
			bucket: 'funstagram',
			access_key_id: Rails.application.secrets.s3_access_key,
			secret_access_key: Rails.application.secrets.s3_secret_key
		}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user
	has_and_belongs_to_many :tags
	has_many :likes

	include PublicActivity::Common

	def tag_names
	end

	def tag_names=(tag_list)
		tag_list.split(', ').each do |tag|
			tags << Tag.find_or_create_by(name: tag)
		end
	end


end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
	validates :name, uniqueness: true

	def to_param
		name
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts
  acts_as_follower
  acts_as_followable

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@post = Post.find params[:post_id]
		like = @post.likes.create
		like.create_activity(:liked, owner: current_user, recipient: @post)
		WebsocketRails[:likes].trigger 'new', {post_id: @post.id, new_like_count: @post.likes.count}

		redirect_to '/posts'
	end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def show
		@post = Post.find params[:post_id]
	end


end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	before_action :authenticate_user!

	def index
		@activities = PublicActivity::Activity.all.select do |activity|
			current_user.following_users.include? activity.owner	
		end

		
		# @activities = PublicActivity::Activity.where(owner_id: current_user.following_users)

		# raise current_user.following_users.inspect
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	before_action :authenticate_admin!

	def index
		@orders = Order.all
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def new
	end

	def create
		@user = current_user
		@post = @user.posts.create post_params
		@post.create_activity(:posted, owner: current_user)
		redirect_to '/posts'
	end

	def index
		@posts = Post.all 
	end

	def show
		@post = Post.find params[:id]
	end

	def destroy
		@post = Post.find params[:id]
		@post.destroy!
		redirect_to '/posts'
	end

	private

	def post_params
		params.require(:post).permit(:title, :image, :tag_names, :address)
	end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find_by_name params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/presence_helper.rb
module PresenceHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/orders/index.html.erb
<% unless @orders.any? %>
	No orders yet
<% else %>

	<% @orders.each do |order| %>
		<%= order.post.title %>
		<%= order.user.email %>
	<% end %>

<% end %>

app/views/posts/_post.html.erb
<div class="col-sm-4">
	<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= post.title %></h3>
      
    </div>
    <div class="panel-body">
    	<div class="image">
			<% if post.image.present? %>
				<%= image_tag post.image.url(:thumb), class: 'upload' %>
				<% end %>
			</div>
			<div class="post-info">
			<% post.tags.each do |tag| %>
				<%= link_to tag.name, tag_path(tag) %>
				<% end %>
			<div class="row">
			<%= link_to 'Map', post_maps_path(post), class: 'btn btn-success' unless post.address.blank? %>
			</div>

			<div class="row text-center">
			<%= link_to 'Buy', new_post_charge_path(post) %>
			</div>

			<div class="row text-center">
			<%= link_to "♥ #{post.likes.count}", post_likes_path(post), class: 'like-button', data: {'post-id' => post.id} %>
			</div>

			</div>

			<% if post.user && user_signed_in? %>
			<p>Posted by <%= post.user.email%></p>
			<% unless current_user.following_users.include? post.user %>
			<p><%= link_to "Follow #{post.user.email}", '#', class: 'follow-button', data: {'to-follow' => post.user.id} %>
			</p>
			<% else %>
			<p><%= "Following #{post.user.email}" %></p>
			<% end %>

			<% end %>

			<% if post.user == current_user %>
			<!-- <a class="btn btn-danger pull-right" href=''> <span class="glyphicon glyphicon-remove"> -->
				<%= link_to "Delete Post", post_path(post), method: :delete %>
			<!-- </span> </button> -->
			<% end %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container" ng-controller="PresenceCtrl">

Currently Signed In: {{members.count}}


<% if @posts.none? %>
	No posts yet
<% else %>

	<% @posts.in_groups_of(3, false) do |post_triplet| %>
		<div class="row">
			<%= render post_triplet %>
		</div>
	<% end %>

<% end %>



</div>

app/views/posts/new.html.erb
<div class="container">
<%= form_for Post.new, html: {multipart: true}, data: {role: 'form'} do |f| %>
	
	<div class="row">
	<div class="form-group col-md-6">
	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
	</div>
	</div>

	<div class="row">
	<div class="form-group col-md-6">
	<%= f.label :image %>
	<%= f.file_field :image %>
	</div>
	</div>

	<div class="row">
	<div class="form-group col-md-6">
	<%= f.label :tag_names, 'Tags' %>
	<%= f.text_field :tag_names, autocomplete: :off, data:{role:'tagsinput'}, class: 'form-control', style: {"width" => "500px"} %>
	</div>
	</div>

	<div class="row">
	<div class="form-group col-md-6">
	<%= f.label :address, 'Address' %>
	<%= f.text_field :address, class: 'form-control' %>
	</div>
	</div>

	<div class="row">
	<div class="form-group col-md-6">
	<%= f.button 'Create Post', class: 'btn btn-default' %>
	</div>
	</div>

<% end %>		
</div>

app/views/tags/show.html.erb
<h1>posts tagged <%= @tag.name %> </h1>

<div class="container">
<% @tag.posts.in_groups_of(3, false) do |post_triplet| %>
	<div class="row">
		<%= render post_triplet %>
	</div>
<% end %>
</div>