config/routes.rb
Rails.application.routes.draw do
	devise_for :users  
  devise_for :admins
  root to: 'posts#index'

  post 'pusher/auth' => 'presence#auth'
  
  resources :posts do
  	resource :maps
  	resources :charges
  	resources :likes
  end

  resources :news

  resources :follows

  resources :orders
  resources :tags

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post

  include PublicActivity::Common
  # tracked

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_create :send_confirmation_email

  def send_confirmation_email
  	OrderMailer.confirmation(self).deliver
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, 
		styles: {thumb: "300x300>"}, 
		storage: :s3,
		s3_credentials: {
			bucket: 'funstagram',
			access_key_id: Rails.application.secrets.s3_access_key,
			secret_access_key: Rails.application.secrets.s3_secret_key
		}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user
	has_and_belongs_to_many :tags
	has_many :likes

	include PublicActivity::Common

	def tag_names
	end

	def tag_names=(tag_list)
		tag_list.split(', ').each do |tag|
			tags << Tag.find_or_create_by(name: tag)
		end
	end


end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
	validates :name, uniqueness: true

	def to_param
		name
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts
  acts_as_follower
  acts_as_followable

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def show
		@post = Post.find params[:post_id]
	end


end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	before_action :authenticate_user!

	def index
		@activities = PublicActivity::Activity.all.select do |activity|
			current_user.following_users.include? activity.owner	
		end

		
		# @activities = PublicActivity::Activity.where(owner_id: current_user.following_users)

		# raise current_user.following_users.inspect
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find_by_name params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/presence_helper.rb
module PresenceHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_header.html.erb
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Funstagram</a>
      </div>

      <% if !user_signed_in? %>



        <div class="navbar-collapse collapse">
          <%= form_for(User.new, as: :user, url: session_path(:user), html: { class: 'navbar-form navbar-right' }) do |f| %>

            <div class="form-group">
              <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
            </div>

            <%= f.button "Sign in", class: 'btn btn-success' %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default' %>  
          <% end %>
        <% else %>

          <ul class="nav nav-tabs pull-right" role="tablist">
          <li class="active"><a href="/posts">Home</a></li>
          <li><a href="/news">News Feed</a></li>
          <li><a href="<%= new_post_path %>">Post A Picture!</a></li>
          <%= content_tag(:li, link_to("Logout", destroy_user_session_path, method: :delete)) %>
        </ul>

        <% end %>
      </div><!--/.navbar-collapse -->
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Funstagram">
<head>
  <title>Funstagram</title>
  <script src='http://maps.google.com/maps/api/js?sensor=true'></script>
  <%= stylesheet_link_tag 'application' %>
  <script src="http://js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>



  <%= render 'layouts/header' %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>


  <%= render 'layouts/footer' %>

</body>
</html>